name: Test PR

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  test:
    runs-on: ${{ matrix.os }}
    container:
      image: continuumio/miniconda3:latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8==3.8
        python -m pip install pytest==7.1
        python -m pip install pytest-flake8==1.1
        python -m pip install pytest-pydocstyle==2.3
        python -m pip install pytest-cov==3.0
        python -m pip install pandas==1.5
        python -m pip install screed==1.0
        python -m pip install .
        conda install -c conda-forge -c bioconda pblat=2.5 -y
    - name: Test with pytest
      run: |
        pytest -v --flake8 --pydocstyle --cov=president --cov-fail-under=90 --cov-report html
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
